document.write('<header><h1> HEADING </h1></header>');
document.write('<aside><p>IN ALMOST EVERY COMPILATION A GREAT VARIETY OF ARRANGEMENTS FOR THE SUCCESSION OF THE PROCESSES IS POSSIBLE, AND VARIOUS CONSIDERATIONS MUST INFLUENCE THE SELACTIONS AMONGST THEM FOR THE PURPOSES OD A CALCULATING ENGINE</p></aside>');
document.write('<section><p>I NEVER AM REALLY SATISFIED THAT I UNDERSTAND AND ANYTHING; BECAUSE, UNDERSTAND AND IT WELL AS I MAY. MY COMPRENHENSION CAN ONLY BE AN INFINITESIMAL FRACTION OF ALL I WANT TO UNDERSTAND ABOUT THE MANY CONNECTIONS AN RELATIONS WHICH OCCUR TO ME, HOW THE MATTER IN QUIESTION WAS FIRST THOUGHT OF OR ARRIVED AT. ETC. ETC.</p></section>');
document.write('<footer><h1>FOOTER</h1></footer>');


